# What is PyTorch?
It's a Python-based scientific computing package targeted at two sets of audiences:
* A replacement for NumPy to use the power of GPUs
* A deep learning research platform that provides maximum flexibility and speed

### Getting Started
#### Tensors

In [1]:
from __future__ import print_function
import torch

Construct a 5x3 matrix, uninitialized

In [2]:
x = torch.empty(5, 3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


Construct a randomly initialized matrix

In [3]:
x = torch.rand(5, 3)
print(x)

tensor([[0.2415, 0.1257, 0.1595],
        [0.2895, 0.4622, 0.9348],
        [0.5455, 0.9363, 0.3355],
        [0.0732, 0.9812, 0.3353],
        [0.7175, 0.2480, 0.9041]])


Construct a matrix filled zeros and of dtype long

In [4]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


Construct a tensor directly from data

In [5]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


Create a tensor based on an existing tensor

In [6]:
# new_* methods take in sizes
x = x.new_ones(5, 3, dtype=torch.double)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [7]:
# override dtype!
x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[ 0.3923, -2.0271,  0.3169],
        [-1.1676,  0.7823,  0.1194],
        [-0.1969,  0.7958,  0.6949],
        [-0.2272,  2.1355, -0.7096],
        [-0.8631,  1.7415,  0.1328]])


Get its size

In [8]:
print(x.size())

torch.Size([5, 3])


#### Operations

Addtion

In [9]:
y = torch.rand(5, 3)
print(x + y)

tensor([[ 0.8891, -1.8324,  0.4115],
        [-0.7695,  0.8633,  1.0640],
        [ 0.0813,  1.6134,  0.8156],
        [ 0.2170,  2.2516, -0.6531],
        [-0.6431,  2.1165,  1.0604]])


In [10]:
print(torch.add(x, y))

tensor([[ 0.8891, -1.8324,  0.4115],
        [-0.7695,  0.8633,  1.0640],
        [ 0.0813,  1.6134,  0.8156],
        [ 0.2170,  2.2516, -0.6531],
        [-0.6431,  2.1165,  1.0604]])


In [11]:
# providing an output tensor as argument
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 0.8891, -1.8324,  0.4115],
        [-0.7695,  0.8633,  1.0640],
        [ 0.0813,  1.6134,  0.8156],
        [ 0.2170,  2.2516, -0.6531],
        [-0.6431,  2.1165,  1.0604]])


In [12]:
# addition in-place
y.add_(x)
print(y)

tensor([[ 0.8891, -1.8324,  0.4115],
        [-0.7695,  0.8633,  1.0640],
        [ 0.0813,  1.6134,  0.8156],
        [ 0.2170,  2.2516, -0.6531],
        [-0.6431,  2.1165,  1.0604]])


Any operation that mutates a tensor in-place is post-fixed with an _

Use __torch.view__ to resize/reshape tensor

In [13]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 2) # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([8, 2])


If you have a one element tensor, use __.item()__ to get the value as a Python number

In [14]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([0.2808])
0.28079676628112793


### NumPy Bridge

#### Converting a Torch Tensor to a NumPy array and vice versa is a breeze.

__The Torch Tensor and NumPy array will share their underlying memory locations (if the Torch Tensor is on CPU), and changing one will change the other.__


In [15]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [16]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


See how NumPy array changed in value

In [17]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


#### Converting NumPy array to Torch Tensor

In [18]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


__All the Tensors on the CPU except a CharTensor support converting to NumPy and back.__